#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 07a959c
#
Name     : compat-pangomm-soname14
Version  : 2.46.4
Release  : 16
URL      : https://download.gnome.org/sources/pangomm/2.46/pangomm-2.46.4.tar.xz
Source0  : https://download.gnome.org/sources/pangomm/2.46/pangomm-2.46.4.tar.xz
Summary  : C++ binding for Pango, not installed
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: compat-pangomm-soname14-lib = %{version}-%{release}
Requires: compat-pangomm-soname14-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : compat-glibmm-soname24-dev
BuildRequires : doxygen
BuildRequires : glibmm-dev
BuildRequires : pkgconfig(cairomm-1.0)
BuildRequires : pkgconfig(mm-common-libstdc++)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory contains files not tracked by a source code control program,
The files can have one of two origins.

%package dev
Summary: dev components for the compat-pangomm-soname14 package.
Group: Development
Requires: compat-pangomm-soname14-lib = %{version}-%{release}
Provides: compat-pangomm-soname14-devel = %{version}-%{release}
Requires: compat-pangomm-soname14 = %{version}-%{release}

%description dev
dev components for the compat-pangomm-soname14 package.


%package lib
Summary: lib components for the compat-pangomm-soname14 package.
Group: Libraries
Requires: compat-pangomm-soname14-license = %{version}-%{release}

%description lib
lib components for the compat-pangomm-soname14 package.


%package license
Summary: license components for the compat-pangomm-soname14 package.
Group: Default

%description license
license components for the compat-pangomm-soname14 package.


%prep
%setup -q -n pangomm-2.46.4
cd %{_builddir}/pangomm-2.46.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742509615
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/compat-pangomm-soname14
cp %{_builddir}/pangomm-%{version}/COPYING %{buildroot}/usr/share/package-licenses/compat-pangomm-soname14/cf756914ec51f52f9c121be247bfda232dc6afd2 || :
cp %{_builddir}/pangomm-%{version}/COPYING.tools %{buildroot}/usr/share/package-licenses/compat-pangomm-soname14/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib64/pangomm-1.4/proc/m4/convert.m4
/usr/lib64/pangomm-1.4/proc/m4/convert_pango.m4
/usr/lib64/pangomm-1.4/proc/m4/convert_pangomm.m4

%files dev
%defattr(-,root,root,-)
/usr/include/pangomm-1.4/pangomm.h
/usr/include/pangomm-1.4/pangomm/attributes.h
/usr/include/pangomm-1.4/pangomm/attriter.h
/usr/include/pangomm-1.4/pangomm/attrlist.h
/usr/include/pangomm-1.4/pangomm/cairofontmap.h
/usr/include/pangomm-1.4/pangomm/color.h
/usr/include/pangomm-1.4/pangomm/context.h
/usr/include/pangomm-1.4/pangomm/coverage.h
/usr/include/pangomm-1.4/pangomm/font.h
/usr/include/pangomm-1.4/pangomm/fontdescription.h
/usr/include/pangomm-1.4/pangomm/fontface.h
/usr/include/pangomm-1.4/pangomm/fontfamily.h
/usr/include/pangomm-1.4/pangomm/fontmap.h
/usr/include/pangomm-1.4/pangomm/fontmetrics.h
/usr/include/pangomm-1.4/pangomm/fontset.h
/usr/include/pangomm-1.4/pangomm/glyph.h
/usr/include/pangomm-1.4/pangomm/glyphstring.h
/usr/include/pangomm-1.4/pangomm/init.h
/usr/include/pangomm-1.4/pangomm/item.h
/usr/include/pangomm-1.4/pangomm/language.h
/usr/include/pangomm-1.4/pangomm/layout.h
/usr/include/pangomm-1.4/pangomm/layoutiter.h
/usr/include/pangomm-1.4/pangomm/layoutline.h
/usr/include/pangomm-1.4/pangomm/layoutrun.h
/usr/include/pangomm-1.4/pangomm/private/attributes_p.h
/usr/include/pangomm-1.4/pangomm/private/attriter_p.h
/usr/include/pangomm-1.4/pangomm/private/attrlist_p.h
/usr/include/pangomm-1.4/pangomm/private/cairofontmap_p.h
/usr/include/pangomm-1.4/pangomm/private/color_p.h
/usr/include/pangomm-1.4/pangomm/private/context_p.h
/usr/include/pangomm-1.4/pangomm/private/coverage_p.h
/usr/include/pangomm-1.4/pangomm/private/font_p.h
/usr/include/pangomm-1.4/pangomm/private/fontdescription_p.h
/usr/include/pangomm-1.4/pangomm/private/fontface_p.h
/usr/include/pangomm-1.4/pangomm/private/fontfamily_p.h
/usr/include/pangomm-1.4/pangomm/private/fontmap_p.h
/usr/include/pangomm-1.4/pangomm/private/fontmetrics_p.h
/usr/include/pangomm-1.4/pangomm/private/fontset_p.h
/usr/include/pangomm-1.4/pangomm/private/glyph_p.h
/usr/include/pangomm-1.4/pangomm/private/glyphstring_p.h
/usr/include/pangomm-1.4/pangomm/private/item_p.h
/usr/include/pangomm-1.4/pangomm/private/language_p.h
/usr/include/pangomm-1.4/pangomm/private/layout_p.h
/usr/include/pangomm-1.4/pangomm/private/layoutiter_p.h
/usr/include/pangomm-1.4/pangomm/private/layoutline_p.h
/usr/include/pangomm-1.4/pangomm/private/layoutrun_p.h
/usr/include/pangomm-1.4/pangomm/private/rectangle_p.h
/usr/include/pangomm-1.4/pangomm/private/renderer_p.h
/usr/include/pangomm-1.4/pangomm/private/tabarray_p.h
/usr/include/pangomm-1.4/pangomm/rectangle.h
/usr/include/pangomm-1.4/pangomm/renderer.h
/usr/include/pangomm-1.4/pangomm/tabarray.h
/usr/include/pangomm-1.4/pangomm/types.h
/usr/include/pangomm-1.4/pangomm/wrap_init.h
/usr/lib64/libpangomm-1.4.so
/usr/lib64/pangomm-1.4/include/pangommconfig.h
/usr/lib64/pkgconfig/pangomm-1.4.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpangomm-1.4.so.1
/usr/lib64/libpangomm-1.4.so.1.0.30

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-pangomm-soname14/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/compat-pangomm-soname14/cf756914ec51f52f9c121be247bfda232dc6afd2
